# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    always_declare_return_types: false # Unnecessary type arguments in const instance creation.
    always_put_control_body_on_new_line: false # Statement should be on a separate line.
    always_put_required_named_parameters_first: false # Required named parameters should be before optional named parameters.
    always_require_non_null_named_parameters: true
    always_specify_types: false # Missing type annotation.
    always_use_package_imports: false # se 'package:' imports for files in the `lib` directory.
    annotate_overrides: true
    avoid_annotating_with_dynamic: false # Unnecessary `dynamic` type annotation.
    avoid_as: true
    avoid_bool_literals_in_conditional_expressions: false # Conditional expressions with a `bool` literal can be simplified.
    avoid_catches_without_on_clauses: false # Catch clause needs to use `on` to specify the type of exception being caught.
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: false # Classes should define instance members.
    avoid_double_and_int_checks: false # Explicit check for double and int value types.
    avoid_dynamic_calls: false # Method invocation or property access on a `dynamic` target.
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes:
      ignore_for_file:
        - lib/l10n/*.dart
        - lib/generated/*.dart # must be ignored for items generated from arb files
    avoid_field_initializers_in_const_classes: false # Fields in 'const' classes should not have initializers.
    avoid_final_parameters: true # This rule is suppressed with ignore_for_file in some generated code.
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: false # Classes that override `==` should not be implemented.
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: false # Multiple variables declared on a single line.
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: false # `bool` parameters should be named parameters.
    avoid_print: false # Don't invoke `print` in production code.
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_types_on_closure_parameters: false # This rule is incompatible with the rule 'always_specify_types'
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: false # The return type should be `Future` when nothing is returned from an `async` function.
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cancel_subscriptions: true
    cascade_invocations: false # Unnecessary duplication of receiver.
    cast_nullable_to_non_nullable: false # Don't cast a nullable value to a non-nullable type.
    close_sinks: true
    combinators_ordering: false # Sort combinators names alphabetically.
    conditional_uri_does_not_exist: true
    constant_identifier_names: false # The constant name `VARIABLE` isn't a lowerCamelCase identifier.
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: false # The imported package 'http_parser' isn't a dependency of the importing package.
    deprecated_consistency: true
    deprecated_member_use_from_same_package: true
    diagnostic_describe_all_properties: false # The public property isn't described by either `debugFillProperties` or `debugDescribeChildren`.
    directives_ordering: false # Disabled for flutter_import_sorter's functionality.
    discarded_futures: false # Asynchronous function invoked in a non-`async` function.
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    enable_null_safety: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    hash_and_equals: true
    implementation_imports: false # Try importing a public library that exports this library, or removing the import.
    implicit_call_tearoffs: true
    implicit_reopen: true
    invalid_case_patterns: true
    invariant_booleans: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_annotations: true
    library_names: true
    library_prefixes: true
    library_private_types_in_public_api: true
    lines_longer_than_80_chars: false # The line length exceeds the 80-character limit.
    literal_only_boolean_expressions: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_default_cases: false # Invalid use of `default` member in a switch.
    no_duplicate_case_values: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_literal_bool_comparisons: false # Don't compare booleans to boolean literals.
    no_logic_in_create_state: true
    non_constant_identifier_names: true
    noop_primitive_operations: false # Classes that override '==' should not be implemented.
    null_check_on_nullable_type_parameter: true
    null_closures: true
    omit_local_variable_types: false # This rule is weighted less heavily for the flutter codebase.
    one_member_abstracts: true
    only_throw_errors: false # Don't throw instances of classes that don't extend either `Exception` or `Error`.
    overridden_fields: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: false # Invalid assignment to the parameter.
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_bool_in_asserts: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: false # Static method should be a constructor.
    prefer_contains: true
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: false # Unnecessary use of a block function body.
    prefer_final_fields: true
    prefer_final_in_for_each: false # The variable iterable_contains_unrelated_type should be final.
    prefer_final_locals: false # This rule is incompatible with the rule 'unnecessary_final_local'.
    prefer_final_parameters: false # This rule is incompatible with the rule 'avoid_final_parameters'
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: false # Unnecessary use of a `double` literal.
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_mixin: true
    prefer_null_aware_method_calls: false # Use a null-aware invocation of the `call` method rather than explicitly testing for `null`.
    prefer_null_aware_operators: true
    prefer_relative_imports: false # This rule is incompatible with `always_use_package_imports`.
    prefer_single_quotes: false
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    public_member_api_docs: false # Missing Documentation for a public member. Good for `dart-doc`. but seems annoying for now. Revisit later.
    recursive_getters: true
    require_trailing_commas: false # Missing a required trailing comma.
    secure_pubspec_urls: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    sort_constructors_first: false # Try moving the constructor declaration before all other members.
    sort_pub_dependencies: false # Try sorting the dependencies. It screws well-commented dependencies documentations.
    sort_unnamed_constructors_first: true
    super_goes_last: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: false # Missing type annotation on a public API.
    type_init_formals: true
    type_literal_in_constant_pattern: true
    unawaited_futures: false # Missing an `await` for the `Future` computed by this expression.
    unnecessary_await_in_return: false # Unnecessary `await`.
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_final: false # Local variables should not be marked as `final`.
    unnecessary_getters_setters: true
    unnecessary_lambdas: false # Closure should be a tearoff.
    unnecessary_late: true
    unnecessary_library_directive: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: false # Unnecessary use of parentheses.
    unnecessary_raw_strings: false # Unnecessary use of raw string.
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: false # Unnecessary use of `toList` in a spread.
    unreachable_from_main: true
    unsafe_html: false # Avoid unsafe HTML APIs (assigning attribute).
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: false # Use a raw string to avoid using escapes.
    use_rethrow_when_possible: true
    use_setters_to_change_properties: false # Method is used to change a property. Document it as a setter instead of as a method.
    use_string_buffers: true
    use_string_in_part_of_directives: false # The part-of directive uses a library name.
    use_super_parameters: false # Convert variable to a super parameter.
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true
