targets:
  $default:
    builders:
      json_serializable:
        options:
          # 패키지 내 `@JsonSerializable` 주석이 달린
          # 모든 클래스의 소스 코드 생성 방법을 구성하는 옵션
          # 각각의 기본값이 나열됩니다.
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: true
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: false
