# run `flutter gen-l10n` after updating arb files
arb-dir: lib/l10n
output-class: Localized
output-dir: lib/gen/l10n
output-localization-file: app_localizations.dart
preferred-supported-locales: [ko]
project-dir: lib
synthetic-package: false
template-arb-file: app_ko.arb
use-escaping: false
