name: wegooli_friends

version: 1.0.1+27

description: Wegooli Friends 프로젝트

# 다음 줄은 `flutter pub publish`를 사용하여 패키지가 실수로 pub.dev에 게시되는 것을 방지함.
# 이는 비공개 패키지의 경우 선호됨.
publish_to: none
# pub.dev에 게시하려면 이 줄을 제거.
# 다음은 애플리케이션의 버전 및 빌드 번호를 정의함.
# 버전 번호는 1.2.43과 같이 점으로 구분된 세 개의 숫자와 +로 구분된 선택적 빌드 번호로 구성됨.
# 버전과 빌드 번호는 각각 --build-name과 --build-number를 지정하여 플래터 빌드에서 재정의할 수 있음.
# 안드로이드에서 빌드명은 버전 이름으로, 빌드 번호는 버전 코드로 사용됨.
# Android 버전 관리에 대한 자세한 내용은 https://developer.android.com/studio/publish/versioning 에서 확인.
# iOS에서 빌드명은 CFBundleShortVersionString으로, 빌드번호는 CFBundleVersion으로 사용됨.
# iOS 버전 관리에 대한 자세한 내용은
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windows에서 빌드명은 제품 및 파일 버전의 메이저, 마이너, 패치 부분으로 사용되며 빌드번호는 빌드 접미사로 사용됨.
homepage: www.wegooli.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

# 종속성은 패키지가 작동하기 위해 필요한 다른 패키지를 지정.
# 패키지 종속성을 최신 버전으로 자동 업그레이드하려면 `flutter pub upgrade --major-versions`를 실행하는 것이 좋음.
# 또는 아래의 버전 번호를 pub.dev에서 사용 가능한 최신 버전으로 변경하여 # 종속성을 수동으로 업데이트할 수 있음.
# 사용 가능한 최신 버전이 있는 종속성을 확인하려면 `flutter pub outdated`를 실행함.
dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  catcher_2: ^1.0.0-alpha.1
  collection: ^1.17.1
  color: ^3.0.0
  connectivity_plus: ^4.0.2
  credit_card_validator: ^2.1.0
  dash_chat_2: ^0.0.18
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.6
  firebase_messaging: ^14.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+2
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.4
  get: ^4.6.5
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  intl: any
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  kpostal: ^0.5.1
  local_auth: ^2.1.7
  logger: ^1.4.0
  lottie: ^2.6.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  rive: ^0.11.4
  sendbird_sdk: ^3.2.17
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner: any
  build_web_compilers: ^4.0.3
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  test: ^1.24.3

# 이 파일의 일반 Dart 부분에 대한 자세한 내용은 다음 페이지(https://dart.dev/tools/pub/pubspec)를 참조.
# 다음 섹션은 Flutter 패키지에 대한 세부 설정.
flutter:
  # 다음 줄은 머티리얼 아이콘 폰트가 애플리케이션에 포함되어 있는지 확인하여 머티리얼 아이콘 클래스에서 아이콘을 사용할 수 있도록 함.
  uses-material-design: true

  # https://github.com/FlutterGen/flutter_gen/blob/main/README.md#error-with-internationalization
  # FlutterGen이 internationalization 충돌시, pubspec.yaml의 generate 설정을 삭제해줘야 함.
  # l10n.yml 파일의 synthetic-package: false 설정.
  generate: true

  # 애플리케이션에 에셋을 추가하려면 다음과 같이 에셋 섹션을 추가함:
  assets:
    - assets/
    - assets/brand/
    - assets/cars/
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/rive/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 400
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 400
    - family: CookieRun
      fonts:
        - asset: assets/fonts/CookieRun Black.otf
        - asset: assets/fonts/CookieRun Bold.otf
        - asset: assets/fonts/CookieRun Regular.otf
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 400
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Regular.otf

# flutter_gen_runner는 자산, 폰트, 색상 등을 위한 Flutter 코드 생성기로, 문자열 기반 API를 없애줌.
# String 기반으로 자산 경로를 사용하는 것은 안전하지 않음.
# build_runner와 FlutterGen을 패키지의 pubspec.yaml 파일에 추가하고,
# Homebrew 또는 Pub Global activate를 사용하여 FlutterGen CLI binary를 설치.
# https://pub.dev/packages/flutter_gen_runner
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: ColorConstant
    inputs:
      - assets/colors/friends.xml # Figma From Wegooli Friends

# Usage:
#   dart run import_sorter:main -e
import_sorter:
  emojis: true # Optional, defaults to false

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
  exclude:
    - bin/cache/**
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/gen/*.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/injector.config.dart"
    - "**/test/*.dart"

# 아이콘 생성 원할 시, dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: assets/icons/WegooliFriends.png
  ios: true
  remove_alpha_ios: true
  android: ic_launcher
  min_sdk_android: 21
  web:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#FFE142"
  image: assets/images/img_gooli_1.png
  branding: assets/brand/wegooli.png
  branding_mode: bottom
  android_12:
    image: assets/images/img_gooli_1.png
    color: "#FFE142"
    branding: assets/brand/wegooli.png
