# 자동 서식 지정 친화적인 마크다운린트 구성(모든 서식 지정 규칙 비활성화)
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false
MD042: false
MD025: false
MD001: false
MD036: false
MD049: false
MD024: false
